In [82]:
import pandas as pd
import numpy as np
np.random.seed(0)
import matplotlib as plt 
import  csv
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier


from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline
from model_code import run_model

from sklearn.model_selection import cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

from sklearn.metrics import roc_curve, auc
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import classification_report

from sklearn import svm
from sklearn import tree
from sklearn import metrics


from sklearn.metrics import accuracy_score

import warnings
warnings.simplefilter("ignore", UserWarning)

In [83]:
df = pd.read_csv('TravelInsurancePrediction.csv')
df.drop(df.columns[[0]], axis=1, inplace=True)
df.head(10)

Age               Employment Type GraduateOrNot  AnnualIncome  \
0   31             Government Sector           Yes        400000   
1   31  Private Sector/Self Employed           Yes       1250000   
2   34  Private Sector/Self Employed           Yes        500000   
3   28  Private Sector/Self Employed           Yes        700000   
4   28  Private Sector/Self Employed           Yes        700000   
5   25  Private Sector/Self Employed            No       1150000   
6   31             Government Sector           Yes       1300000   
7   31  Private Sector/Self Employed           Yes       1350000   
8   28  Private Sector/Self Employed           Yes       1450000   
9   33             Government Sector           Yes        800000   

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0              6                1            No                  No   
1              7                0            No                  No   
2              4                1            No                  No   
3              3                1            No                  No   
4              8                1           Yes                  No   
5              4                0            No                  No   
6              4                0            No                  No   
7              3                0           Yes                 Yes   
8              6                1           Yes                 Yes   
9              3                0           Yes                  No   

   TravelInsurance  
0                0  
1                0  
2                1  
3                0  
4                0  
5                0  
6                0  
7                1  
8                1  
9                0

In [84]:
def run_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)

    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)    
    cnf_matrix_test = confusion_matrix(y_test,  y_pred_test)

    print('Confusion Matrix for Test Set:\n', cnf_matrix_test)
   
    cnf_matrix_train = confusion_matrix(y_train,  y_pred_train)
    print('Confusion Matrix for Train Set:\n', cnf_matrix_train)
 
    print('Classification Report for Test Set:\n',classification_report(y_test , y_pred_test))
    print('Classification Report for Train Set:\n',classification_report(y_train, y_pred_train))
    return model 

In [85]:
y = df.pop('TravelInsurance')
X_train, X_test, y_train, y_test = train_test_split(
    df, y, test_size=0.2, random_state=42)

In [86]:
X_train_nums=X_train.select_dtypes('float64')
X_train_cat = X_train.select_dtypes('object')

In [87]:
numerical_pipeline = Pipeline(steps=[
    ('ss', StandardScaler())
])
                
categorical_pipeline = Pipeline(steps=[
    ('ohe', OneHotEncoder(drop='first',
                         sparse=False))
])

trans = ColumnTransformer(transformers=[
    ('numerical', numerical_pipeline, X_train_nums.columns),
    ('categorical', categorical_pipeline, X_train_cat.columns)
])

baseline models 

In [117]:
base_model_pipe_lr = Pipeline(steps=[
    ('trans', trans),
    ('lr', LogisticRegression())
])
run_model(base_model_pipe_lr, X_train, X_test, y_train, y_test)

Confusion Matrix for Test Set:
 [[238  19]
 [ 82  59]]
Confusion Matrix for Train Set:
 [[957  63]
 [330 239]]
Classification Report for Test Set:
               precision    recall  f1-score   support

           0       0.74      0.93      0.82       257
           1       0.76      0.42      0.54       141

    accuracy                           0.75       398
   macro avg       0.75      0.67      0.68       398
weighted avg       0.75      0.75      0.72       398

Classification Report for Train Set:
               precision    recall  f1-score   support

           0       0.74      0.94      0.83      1020
           1       0.79      0.42      0.55       569

    accuracy                           0.75      1589
   macro avg       0.77      0.68      0.69      1589
weighted avg       0.76      0.75      0.73      1589



Pipeline(steps=[('trans',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('ss',
                                                                   StandardScaler())]),
                                                  Index([], dtype='object')),
                                                 ('categorical',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse=False))]),
                                                  Index(['Employment Type', 'GraduateOrNot', 'FrequentFlyer',
       'EverTravelledAbroad'],
      dtype='object'))])),
                ('lr', LogisticRegression())])

In [118]:
base_model_pipe_knn = Pipeline(steps=[
    ('trans', trans),
    ('knn', KNeighborsClassifier())
])
run_model(base_model_pipe_knn, X_train, X_test, y_train, y_test)



Confusion Matrix for Test Set:
 [[240  17]
 [ 91  50]]
Confusion Matrix for Train Set:
 [[978  42]
 [344 225]]
Classification Report for Test Set:
               precision    recall  f1-score   support

           0       0.73      0.93      0.82       257
           1       0.75      0.35      0.48       141

    accuracy                           0.73       398
   macro avg       0.74      0.64      0.65       398
weighted avg       0.73      0.73      0.70       398

Classification Report for Train Set:
               precision    recall  f1-score   support

           0       0.74      0.96      0.84      1020
           1       0.84      0.40      0.54       569

    accuracy                           0.76      1589
   macro avg       0.79      0.68      0.69      1589
weighted avg       0.78      0.76      0.73      1589



Pipeline(steps=[('trans',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('ss',
                                                                   StandardScaler())]),
                                                  Index([], dtype='object')),
                                                 ('categorical',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse=False))]),
                                                  Index(['Employment Type', 'GraduateOrNot', 'FrequentFlyer',
       'EverTravelledAbroad'],
      dtype='object'))])),
                ('knn', KNeighborsClassifier())])

In [119]:
base_model_pipe_nb = Pipeline(steps=[
    ('trans', trans),
    ('nb', GaussianNB())
])
run_model(base_model_pipe_nb, X_train, X_test, y_train, y_test)

Confusion Matrix for Test Set:
 [[215  42]
 [ 72  69]]
Confusion Matrix for Train Set:
 [[876 144]
 [294 275]]
Classification Report for Test Set:
               precision    recall  f1-score   support

           0       0.75      0.84      0.79       257
           1       0.62      0.49      0.55       141

    accuracy                           0.71       398
   macro avg       0.69      0.66      0.67       398
weighted avg       0.70      0.71      0.70       398

Classification Report for Train Set:
               precision    recall  f1-score   support

           0       0.75      0.86      0.80      1020
           1       0.66      0.48      0.56       569

    accuracy                           0.72      1589
   macro avg       0.70      0.67      0.68      1589
weighted avg       0.72      0.72      0.71      1589



Pipeline(steps=[('trans',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('ss',
                                                                   StandardScaler())]),
                                                  Index([], dtype='object')),
                                                 ('categorical',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse=False))]),
                                                  Index(['Employment Type', 'GraduateOrNot', 'FrequentFlyer',
       'EverTravelledAbroad'],
      dtype='object'))])),
                ('nb', GaussianNB())])

In [120]:
base_model_pipe_dt = Pipeline(steps=[
    ('trans', trans),
    ('dt', DecisionTreeClassifier())
])
run_model(base_model_pipe_dt, X_train, X_test, y_train, y_test)

Confusion Matrix for Test Set:
 [[240  17]
 [ 91  50]]
Confusion Matrix for Train Set:
 [[978  42]
 [344 225]]
Classification Report for Test Set:
               precision    recall  f1-score   support

           0       0.73      0.93      0.82       257
           1       0.75      0.35      0.48       141

    accuracy                           0.73       398
   macro avg       0.74      0.64      0.65       398
weighted avg       0.73      0.73      0.70       398

Classification Report for Train Set:
               precision    recall  f1-score   support

           0       0.74      0.96      0.84      1020
           1       0.84      0.40      0.54       569

    accuracy                           0.76      1589
   macro avg       0.79      0.68      0.69      1589
weighted avg       0.78      0.76      0.73      1589



Pipeline(steps=[('trans',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('ss',
                                                                   StandardScaler())]),
                                                  Index([], dtype='object')),
                                                 ('categorical',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse=False))]),
                                                  Index(['Employment Type', 'GraduateOrNot', 'FrequentFlyer',
       'EverTravelledAbroad'],
      dtype='object'))])),
                ('dt', DecisionTreeClassifier())])

In [121]:
base_model_pipe_rf = Pipeline(steps=[
    ('trans', trans),
    ('rf', RandomForestClassifier())
])
run_model(base_model_pipe_rf, X_train, X_test, y_train, y_test)

Confusion Matrix for Test Set:
 [[240  17]
 [ 91  50]]
Confusion Matrix for Train Set:
 [[978  42]
 [344 225]]
Classification Report for Test Set:
               precision    recall  f1-score   support

           0       0.73      0.93      0.82       257
           1       0.75      0.35      0.48       141

    accuracy                           0.73       398
   macro avg       0.74      0.64      0.65       398
weighted avg       0.73      0.73      0.70       398

Classification Report for Train Set:
               precision    recall  f1-score   support

           0       0.74      0.96      0.84      1020
           1       0.84      0.40      0.54       569

    accuracy                           0.76      1589
   macro avg       0.79      0.68      0.69      1589
weighted avg       0.78      0.76      0.73      1589



Pipeline(steps=[('trans',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('ss',
                                                                   StandardScaler())]),
                                                  Index([], dtype='object')),
                                                 ('categorical',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse=False))]),
                                                  Index(['Employment Type', 'GraduateOrNot', 'FrequentFlyer',
       'EverTravelledAbroad'],
      dtype='object'))])),
                ('rf', RandomForestClassifier())])

In [116]:
base_model_pipe_xg = Pipeline(steps=[
    ('trans', trans),
    ('xg', XGBClassifier())
])
run_model(base_model_pipe_xg, X_train, X_test, y_train, y_test)

Confusion Matrix for Test Set:
 [[240  17]
 [ 91  50]]
Confusion Matrix for Train Set:
 [[978  42]
 [344 225]]
Classification Report for Test Set:
               precision    recall  f1-score   support

           0       0.73      0.93      0.82       257
           1       0.75      0.35      0.48       141

    accuracy                           0.73       398
   macro avg       0.74      0.64      0.65       398
weighted avg       0.73      0.73      0.70       398

Classification Report for Train Set:
               precision    recall  f1-score   support

           0       0.74      0.96      0.84      1020
           1       0.84      0.40      0.54       569

    accuracy                           0.76      1589
   macro avg       0.79      0.68      0.69      1589
weighted avg       0.78      0.76      0.73      1589



Pipeline(steps=[('trans',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('ss',
                                                                   StandardScaler())]),
                                                  Index([], dtype='object')),
                                                 ('categorical',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse=False))]),
                                                  Index(['Employment Type', 'GraduateOrNot', 'FrequentFlyer',
       'EverTravelledAbroad'],
      dtype='object'))])),
                ('xg',
                 XGBClassifier(base_score=...
                               colsample_bytree=1, gamma=0, gpu_id=-1,
                               

GridSearch Models 

In [123]:
model_pipe_lr = Pipeline(steps=[
    ('trans', trans),
    ('lr', LogisticRegression())
])
pipe_grid_lr = {'lr__C': (0.01, 0.1, 1, 10),
    'lr__fit_intercept': (True, False)}

gs_pipe_lr = GridSearchCV(estimator=model_pipe_lr, param_grid=pipe_grid_lr,cv=5)
run_model(gs_pipe_lr, X_train, X_test, y_train, y_test)

Confusion Matrix for Test Set:
 [[238  19]
 [ 82  59]]
Confusion Matrix for Train Set:
 [[957  63]
 [330 239]]
Classification Report for Test Set:
               precision    recall  f1-score   support

           0       0.74      0.93      0.82       257
           1       0.76      0.42      0.54       141

    accuracy                           0.75       398
   macro avg       0.75      0.67      0.68       398
weighted avg       0.75      0.75      0.72       398

Classification Report for Train Set:
               precision    recall  f1-score   support

           0       0.74      0.94      0.83      1020
           1       0.79      0.42      0.55       569

    accuracy                           0.75      1589
   macro avg       0.77      0.68      0.69      1589
weighted avg       0.76      0.75      0.73      1589



GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trans',
                                        ColumnTransformer(transformers=[('numerical',
                                                                         Pipeline(steps=[('ss',
                                                                                          StandardScaler())]),
                                                                         Index([], dtype='object')),
                                                                        ('categorical',
                                                                         Pipeline(steps=[('ohe',
                                                                                          OneHotEncoder(drop='first',
                                                                                                        sparse=False))]),
                                                                         Index(['Employment Type', 'GraduateOrNot

In [124]:
model_pipe_knn = Pipeline(steps=[
    ('trans', trans),
    ('knn', KNeighborsClassifier())
])
pipe_grid_knn = {'knn__n_neighbors': [3, 5, 7], 'knn__p': [1, 2, 3]}

gs_pipe_knn = GridSearchCV(estimator=model_pipe_knn, param_grid=pipe_grid,cv=5)
run_model(gs_pipe_knn, X_train, X_test, y_train, y_test)

Confusion Matrix for Test Set:
 [[240  17]
 [ 86  55]]
Confusion Matrix for Train Set:
 [[970  50]
 [336 233]]
Classification Report for Test Set:
               precision    recall  f1-score   support

           0       0.74      0.93      0.82       257
           1       0.76      0.39      0.52       141

    accuracy                           0.74       398
   macro avg       0.75      0.66      0.67       398
weighted avg       0.75      0.74      0.71       398

Classification Report for Train Set:
               precision    recall  f1-score   support

           0       0.74      0.95      0.83      1020
           1       0.82      0.41      0.55       569

    accuracy                           0.76      1589
   macro avg       0.78      0.68      0.69      1589
weighted avg       0.77      0.76      0.73      1589



GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trans',
                                        ColumnTransformer(transformers=[('numerical',
                                                                         Pipeline(steps=[('ss',
                                                                                          StandardScaler())]),
                                                                         Index([], dtype='object')),
                                                                        ('categorical',
                                                                         Pipeline(steps=[('ohe',
                                                                                          OneHotEncoder(drop='first',
                                                                                                        sparse=False))]),
                                                                         Index(['Employment Type', 'GraduateOrNot

In [90]:
model_pipe_dt = Pipeline(steps=[
    ('trans', trans),
    ('dt', DecisionTreeClassifier())
])
pipe_grid_dt = {'dt__max_depth': [None, 2, 6, 10], 'dt__min_samples_split': [5, 10]}

gs_pipe_dt = GridSearchCV(estimator=model_pipe_dt, param_grid=pipe_grid_dt,cv=5)
run_model(gs_pipe_dt, X_train, X_test, y_train, y_test)


Confusion Matrix for Test Set:
 [[240  17]
 [ 91  50]]
Confusion Matrix for Train Set:
 [[978  42]
 [344 225]]
Classification Report for Test Set:
               precision    recall  f1-score   support

           0       0.73      0.93      0.82       257
           1       0.75      0.35      0.48       141

    accuracy                           0.73       398
   macro avg       0.74      0.64      0.65       398
weighted avg       0.73      0.73      0.70       398

Classification Report for Train Set:
               precision    recall  f1-score   support

           0       0.74      0.96      0.84      1020
           1       0.84      0.40      0.54       569

    accuracy                           0.76      1589
   macro avg       0.79      0.68      0.69      1589
weighted avg       0.78      0.76      0.73      1589



GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trans',
                                        ColumnTransformer(transformers=[('numerical',
                                                                         Pipeline(steps=[('ss',
                                                                                          StandardScaler())]),
                                                                         Index([], dtype='object')),
                                                                        ('categorical',
                                                                         Pipeline(steps=[('ohe',
                                                                                          OneHotEncoder(drop='first',
                                                                                                        sparse=False))]),
                                                                         Index(['Employment Type', 'GraduateOrNot

In [95]:
model_pipe_rf = Pipeline(steps=[
    ('trans', trans),
    ('rf', RandomForestClassifier())
])
pipe_grid_rf = {'rf__n_estimators': [4, 6, 9], 
              'rf__max_features': ['log2', 'sqrt','auto'],
              'rf__criterion': ['entropy', 'gini'], 
              'rf__max_depth': [2, 3, 5, 10], 
              'rf__min_samples_split': [2, 3, 5],
              'rf__min_samples_leaf': [1,5,8] }

gs_pipe_rf = GridSearchCV(estimator=model_pipe_rf, param_grid=pipe_grid_rf,cv=5)
run_model(gs_pipe_rf, X_train, X_test, y_train, y_test)

Confusion Matrix for Test Set:
 [[239  18]
 [ 81  60]]
Confusion Matrix for Train Set:
 [[946  74]
 [314 255]]
Classification Report for Test Set:
               precision    recall  f1-score   support

           0       0.75      0.93      0.83       257
           1       0.77      0.43      0.55       141

    accuracy                           0.75       398
   macro avg       0.76      0.68      0.69       398
weighted avg       0.75      0.75      0.73       398

Classification Report for Train Set:
               precision    recall  f1-score   support

           0       0.75      0.93      0.83      1020
           1       0.78      0.45      0.57       569

    accuracy                           0.76      1589
   macro avg       0.76      0.69      0.70      1589
weighted avg       0.76      0.76      0.74      1589



GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trans',
                                        ColumnTransformer(transformers=[('numerical',
                                                                         Pipeline(steps=[('ss',
                                                                                          StandardScaler())]),
                                                                         Index([], dtype='object')),
                                                                        ('categorical',
                                                                         Pipeline(steps=[('ohe',
                                                                                          OneHotEncoder(drop='first',
                                                                                                        sparse=False))]),
                                                                         Index(['Employment Type', 'GraduateOrNot

In [125]:
model_pipe_xg = Pipeline(steps=[
    ('trans', trans),
    ('xg', XGBClassifier())
])
pipe_grid_xg = {'xg_learning_rate': [0.1, 0.2],
                'xg_max_depth': [6],
                'xg_min_child_weight': [1, 2],
                'xg_subsample': [0.5, 0.7],
                'xg_n_estimators': [100],}

gs_pipe_xg = GridSearchCV(estimator=model_pipe_xg, param_grid=pipe_grid_xg,cv=5)
run_model(gs_pipe_xg, X_train, X_test, y_train, y_test)

ValueError: Invalid parameter xg_learning_rate for estimator Pipeline(steps=[('trans',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('ss',
                                                                   StandardScaler())]),
                                                  Index([], dtype='object')),
                                                 ('categorical',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse=False))]),
                                                  Index(['Employment Type', 'GraduateOrNot', 'FrequentFlyer',
       'EverTravelledAbroad'],
      dtype='object'))])),
                ('xg',
                 XGBClassifier(base_score=...
                               importance_type='gain',
                               interaction_constraints=None, learning_rate=None,
                               max_delta_step=None, max_depth=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, n_estimators=100,
                               n_jobs=None, num_parallel_tree=None,
                               random_state=None, reg_alpha=None,
                               reg_lambda=None, scale_pos_weight=None,
                               subsample=None, tree_method=None,
                               validate_parameters=None, verbosity=None))]). Check the list of available parameters with `estimator.get_params().keys()`.