In [371]:
import pandas as pd
import numpy as np
import matplotlib as plt 
import  csv
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from model_code import run_model
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [372]:
df = pd.read_csv('TravelInsurancePrediction.csv')
df.drop(df.columns[[0]], axis=1, inplace=True)
df.head(10)

Age               Employment Type GraduateOrNot  AnnualIncome  \
0   31             Government Sector           Yes        400000   
1   31  Private Sector/Self Employed           Yes       1250000   
2   34  Private Sector/Self Employed           Yes        500000   
3   28  Private Sector/Self Employed           Yes        700000   
4   28  Private Sector/Self Employed           Yes        700000   
5   25  Private Sector/Self Employed            No       1150000   
6   31             Government Sector           Yes       1300000   
7   31  Private Sector/Self Employed           Yes       1350000   
8   28  Private Sector/Self Employed           Yes       1450000   
9   33             Government Sector           Yes        800000   

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0              6                1            No                  No   
1              7                0            No                  No   
2              4                1            No                  No   
3              3                1            No                  No   
4              8                1           Yes                  No   
5              4                0            No                  No   
6              4                0            No                  No   
7              3                0           Yes                 Yes   
8              6                1           Yes                 Yes   
9              3                0           Yes                  No   

   TravelInsurance  
0                0  
1                0  
2                1  
3                0  
4                0  
5                0  
6                0  
7                1  
8                1  
9                0

In [373]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values



In [374]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2,6,7])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [375]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)


[[ 1.55473609 -1.55473609 -0.41452251 ... -0.05365604  1.38182856
   1.6083866 ]
 [ 1.55473609 -1.55473609 -0.41452251 ...  0.7456513  -1.1034296
  -0.62174107]
 [ 1.55473609 -1.55473609 -0.41452251 ...  0.47921552 -1.1034296
  -0.62174107]
 ...
 [-0.64319598  0.64319598 -0.41452251 ... -1.11939916  0.13919948
   1.6083866 ]
 [-0.64319598  0.64319598 -0.41452251 ...  0.7456513  -1.1034296
  -0.62174107]
 [-0.64319598  0.64319598  2.41241424 ...  0.61243341 -0.48211506
  -0.62174107]]
[[-0.64319598  0.64319598 -0.41452251 ...  1.54495864  0.13919948
   1.6083866 ]
 [ 1.55473609 -1.55473609 -0.41452251 ...  0.7456513   1.38182856
   1.6083866 ]
 [-0.64319598  0.64319598 -0.41452251 ... -0.05365604 -1.1034296
  -0.62174107]
 ...
 [-0.64319598  0.64319598 -0.41452251 ...  1.27852286 -1.72474414
   1.6083866 ]
 [ 1.55473609 -1.55473609  2.41241424 ... -1.65227073  0.76051402
  -0.62174107]
 [ 1.55473609 -1.55473609 -0.41452251 ... -0.05365604  0.76051402
   1.6083866 ]]


In [376]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[234  26]
 [ 67  71]]


0.7663316582914573

In [377]:
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[231  29]
 [ 56  82]]


0.7864321608040201

In [378]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[206  54]
 [ 59  79]]


0.7160804020100503

In [379]:
classifier= DecisionTreeClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[218  42]
 [ 49  89]]


0.7713567839195979

In [380]:
dt_clf = DecisionTreeClassifier()

dt_cv_score = cross_val_score(dt_clf, X_train, y_train, cv=3)
mean_dt_cv_score = np.mean(dt_cv_score)

print(f"Mean Cross Validation Score: {mean_dt_cv_score :.2%}")

Mean Cross Validation Score: 75.27%


In [381]:
classifier_1 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_1.fit(X_train, y_train)
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')


KNeighborsClassifier()

In [382]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[218  42]
 [ 49  89]]


0.7713567839195979

In [385]:
def run_model(model, X_train, X_test, y_train, y_test) :
    import pandas as pd
    import numpy as np
    import matplotlib as plt 
    import  csv
    from sklearn.preprocessing import StandardScaler
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.model_selection import train_test_split, GridSearchCV
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.pipeline import Pipeline
    from model_code import run_model
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import cross_val_score
    print('Training R^2 :', model.score(X_train, y_train))
    y_pred_train = model.predict(X_train)
    #print('Training Root Mean Square Error', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train)))
    print('\n----------------\n')
    print('Testing R^2 :', model.score(X_test, y_test))
    y_pred_test = model.predict(X_test)
   # print('Testing Root Mean Square Error', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test)))
    cnf_matrix = confusion_matrix(y_test, y_hat_test)
    print('Confusion Matrix:\n', cnf_matrix)
    #plot_confusion_matrix(logreg, X_test, y_test,cmap=plt.cm.Blues)
    #plt.show()
    #print(classification_report(y_true, y_pred, target_names=target_names))


In [386]:
run_model(classifier_1, X_train, X_test, y_train, y_test)

Training R^2 : 0.8325991189427313

----------------

Testing R^2 : 0.7864321608040201
Confusion Matrix:
 [[256   4]
 [135   3]]
